# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
gems: [jekyll-paginate,jekyll-gist]
permalink:           pretty

# Setup
title:               Data Blog
tagline:             'Political Science, Big Data, machine learning'
description:         'Not really sure What this site will be yet'
url:                 www.sonoshah.github.io/
baseurl:             /
paginate:            5
paginate_path: "page:num"

# About/contact
author: 
  name:    'Sono Shah'        
  url:               
  email:            

# Custom vars
version:             1.0.0
